exclude: "config/exclude.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config.json"
description: "config/description.md"

build_name: "cladeX"
auspice_name: "monkeypox"

## filter
min_date: 1950
min_length: 10000

## align
max_indel: 10000
seed_spacing: 1000

## refine
root: "min_dev"
clock_rate: 5e-6
clock_std_dev: 3e-6

mask:
  from_beginning: 1500
  from_end: 1000
  maskfile: "config/mask.bed"
