exclude: "config/exclude_outbreak.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config.json"
description: "config/description.md"

build_name: "outbreakClade"
auspice_name: "monkeypox_outbreak"

## filter
min_date: 2017
min_length: 10000

## align
max_indel: 10000
seed_spacing: 1000

## refine
timetree: true
root: "best"

mask:
  from_beginning: 1500
  from_end: 1000
  maskfile: "config/mask.bed"
