include: "config/include_accessions.txt"
exclude: "config/exclude_accessions.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config.json"
description: "config/description.md"
clades: "config/clades.tsv"

strain_id_field: "accession"
display_strain_field: "strain_original"

build_name: "B.1"
auspice_name: "nextclade_mpx_b1_MA001"

## filter
min_date: 1950
min_length: 100000

## align
max_indel: 20000
seed_spacing: 1000

## refine
timetree: false
root: "ON563414"
clock_rate: 5e-6
clock_std_dev: 3e-6

mask:
  from_beginning: 7000 
  from_end: 7000 
  maskfile: "config/mask.bed"
