exclude: "config/exclude_accessions_hmpxv1.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors.tsv"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_hmpxv1.json"
description: "config/description.md"

strain_id_field: "accession"
display_strain_field: "strain_original"

build_name: "hmpxv1"
auspice_name: "monkeypox_hmpxv1"

## filter
min_date: 2017
min_length: 10000

## align
max_indel: 10000
seed_spacing: 1000

## refine
timetree: true
root: "MK783032 MK783030"

## recency
recency: true

mask:
  from_beginning: 1500
  from_end: 7000
  maskfile: "config/mask.bed"
