exclude: "config/exclude_accessions_mpxv.txt"
reference: "config/reference.fasta"
genemap: "config/genemap.gff"
genbank_reference: "config/reference.gb"
colors: "config/colors_hmpxv1.tsv"
clades: "config/clades.tsv"
lat_longs: "config/lat_longs.tsv"
auspice_config: "config/auspice_config_hmpxv1_big.json"
description: "config/description.md"
tree_mask: "config/tree_mask.tsv"

# Use `accession` as the ID column since `strain` currently contains duplicates¹.
# ¹ https://github.com/nextstrain/monkeypox/issues/33
strain_id_field: "accession"
display_strain_field: "strain"

build_name: "hmpxv1_big"
auspice_name: "mpox_lineage-B.1"

## filter
min_date: 2022
min_length: 180000
filter:
  b1:
    group_by: "--group-by year month country"
    sequences_per_group: "--subsample-max-sequences 5000"
    other_filters: "outbreak!=hMPXV-1 clade!=IIb"
    exclude_lineages:
      - A
      - A.1
      - A.1.1
      - A.2
      - A.2.1
      - A.2.2
      - A.2.3
      - A.3

## align
max_indel: 10000
seed_spacing: 1000

## treefix
fix_tree: true
treefix_root: "--root OP890401"

## refine
timetree: true
root: "OP890401"
clock_rate: 5.7e-5
clock_std_dev: 2e-5

## recency
recency: true

mask:
  from_beginning: 800
  from_end: 6422
  maskfile: "config/mask.bed"
